# Generated by Django 3.2.6 on 2021-08-31 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tripulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('grupo', models.CharField(choices=[(0, 'Grupo 1'), (1, 'Grupo 2')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Barco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('embarque', models.DateField()),
                ('desembarque', models.DateField()),
                ('tripulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionBarco.tripulante')),
            ],
        ),
    ]
