# Generated by Django 3.2.5 on 2021-09-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBarco', '0003_alter_tripulante_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripulante',
            name='grupo',
            field=models.CharField(choices=[('1', 'Grupo 1'), ('2', 'Grupo 2')], max_length=50),
        ),
    ]
